Bibdk 2021 107 order
DBCDK/bibliotekdk-next-api pull request #32
Opened 2021-04-28 12:27 UTC by pjohans

2021-04-28 13:37 UTC, kfudbc requested changes
ser godt ud, jeg har et par få forespørgsler

2021-04-28 13:37 UTC, kfudbc commented on src/schema/submitOrder.js
> +    fields: [String!],
jeg synes der er nogle felter der skal fjernes, jeg tror ikke de giver værdi til api'et:
fields, pretty, timings
ved ikke hvad orderType gør, om den er nødvendig?

2021-04-28 13:37 UTC, kfudbc commented on src/schema/submitOrder.js
> +    ],
Sæt gerne udråbstegn efter [String!]!, så er pids ikke optional

2021-04-28 13:39 UTC, mtni approved these changes

2021-05-03 05:45 UTC, kfudbc approved these changes
:100:

2021-05-03 05:59 UTC, merged