BIBDK2021 573 serie service
DBCDK/bibliotekdk-next-api pull request #60
Opened 2021-08-17 14:19 UTC by mtni

https://dbcjira.atlassian.net/browse/BIBDK2021-573

2021-08-17 14:23 UTC, mtni commented on src/schema/work.js
>        return parent;
Jeg har disabled at series kan blive null i "roden" - vi kan lige snakke om det. og så fjerner jeg kode afhængig af hvad vi ender med.

2021-08-17 14:56 UTC, kfudbc requested changes
synes den er meget tæt på, men har lige et par småting

2021-08-17 14:56 UTC, kfudbc commented on src/datasources/series.datasource.js
> +}
vi kunne godt cache serier

2021-08-17 14:56 UTC, kfudbc commented on src/schema/series.js
> +  works: [Work]
Hvad er der galt med [Work!]?
[Work] betyder at der kan returneres en liste med null-values inde i listen: fx [null, {...}]

2021-08-17 14:56 UTC, kfudbc commented on src/schema/work.js
> +      return null;
hvis series ikke må være null, så bliver den gal hvis den når herned til - så skal den returnere tom objekt her.. synes dog det ville være pænere hvis den måtte være null, umiddelbart

2021-08-18 07:59 UTC, kfudbc approved these changes
:100:

2021-08-18 08:03 UTC, merged